[package]
name = "game_of_life"
version = "0.1.0"
authors = ["Zademn <zademnwalves@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
ggez = "0.5.1"
rand = "0.8.3"
rayon = "1.5.0"
